# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorldOfWarcraft', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldOfWarcraftBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='wow/raid/')),
                ('mode', models.PositiveSmallIntegerField(choices=[(1, 'Raid'), (2, 'Dungeon')])),
                ('feature_1', models.CharField(blank=True, max_length=40, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=40, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=40, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftDungeonSimpleOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_dungeon_simple_order', serialize=False, to='accounts.baseorder')),
                ('keystone', models.IntegerField()),
                ('keys', models.IntegerField()),
                ('traders', models.CharField(max_length=300)),
                ('traders_armor_type', models.CharField(max_length=300)),
                ('map_preferred', models.CharField(max_length=300)),
                ('timed', models.BooleanField()),
                ('boost_method', models.CharField(max_length=300)),
                ('maps', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='wow/images/')),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftRpsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_of_2vs2', models.FloatField(default=1)),
                ('price_of_3vs3', models.FloatField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WowLevelUpOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_level_up_order', serialize=False, to='accounts.baseorder')),
                ('current_level', models.IntegerField(blank=True, default=1)),
                ('reached_level', models.IntegerField(blank=True, default=1, null=True)),
                ('desired_level', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WowLevelUpPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.PositiveSmallIntegerField(choices=[(1, 'Vault of the Incarnates'), (2, 'Aberrus, the Shadowed Crucible'), (3, "Amirdrassil, the Dream's Hope")])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('map', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftRaidBundleOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_raid_bundle_order', serialize=False, to='accounts.baseorder')),
                ('loot_priority', models.BooleanField()),
                ('boost_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wow_raid_bundle_order_bundles', to='WorldOfWarcraft.worldofwarcraftbundle')),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftRaidSimpleOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_raid_simple_order', serialize=False, to='accounts.baseorder')),
                ('map', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vault of the Incarnates'), (2, 'Aberrus, the Shadowed Crucible'), (3, "Amirdrassil, the Dream's Hope")], null=True)),
                ('difficulty', models.FloatField()),
                ('loot_priority', models.BooleanField()),
                ('boost_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bosses', models.ManyToManyField(related_name='wow_raid_simple_order_bosses', to='WorldOfWarcraft.worldofwarcraftboss')),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftArenaBoostOrder',
            fields=[
                ('is_arena_2vs2', models.BooleanField(default=True)),
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(default=0)),
                ('reached_division', models.PositiveSmallIntegerField(default=0)),
                ('desired_division', models.PositiveSmallIntegerField(default=0)),
                ('rank1_player', models.BooleanField(default=False)),
                ('tournament_player', models.BooleanField(default=False)),
                ('boost_method', models.CharField(max_length=50)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_current_rank', to='WorldOfWarcraft.worldofwarcraftrank')),
                ('desired_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_desired_rank', to='WorldOfWarcraft.worldofwarcraftrank')),
                ('reached_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_reached_rank', to='WorldOfWarcraft.worldofwarcraftrank')),
            ],
        ),
    ]
