# Generated by Django 5.0.4 on 2025-05-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0003_auto_20250516_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='boost_method',
            field=models.CharField(max_length=50, default='self-play'),
        ),
    ] 