# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_for_admins', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booster_room', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': False}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.IntegerField(choices=[(1, 'normal'), (2, 'tip'), (3, 'changes'), (4, 'admin'), (5, 'refresh')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
