# Generated by Django 5.0.4 on 2025-05-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE accounts_baseorder
            ADD COLUMN real_order_price double precision DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE accounts_baseorder
            DROP COLUMN real_order_price;
            """
        ),
    ]
