# Generated by Django 5.0.4 on 2025-05-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250517_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='real_order_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
