# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearthstoneBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='hearthstone/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneBattlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_0_to_2000', models.FloatField(default=0)),
                ('from_2000_to_4000', models.FloatField(default=0)),
                ('from_4000_to_6000', models.FloatField(default=0)),
                ('from_6000_to_8000', models.FloatField(default=0)),
                ('from_8000_to_10000', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='hearthstone/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HearthStoneBattleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='hearthstone.hearthstonebattle')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='hearthstone.hearthstonebattle')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.baseorder')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='hearthstone.hearthstonebattle')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_3', models.FloatField(default=0)),
                ('marks_2', models.FloatField(default=0)),
                ('marks_1', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='hearthstone.hearthstonerank')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hearthstone_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Stars'), (1, '3 Stars'), (2, '2 Stars'), (3, '1 Stars')], null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Stars'), (1, '3 Stars'), (2, '2 Stars'), (3, '1 Stars')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='hearthstone.hearthstonerank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='hearthstone.hearthstonerank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='hearthstone.hearthstonerank')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_X_to_IX', models.FloatField(default=0)),
                ('from_IX_to_VIII', models.FloatField(default=0)),
                ('from_VIII_to_VII', models.FloatField(default=0)),
                ('from_VII_to_VI', models.FloatField(default=0)),
                ('from_VI_to_V', models.FloatField(default=0)),
                ('from_V_to_IV', models.FloatField(default=0)),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='hearthstone.hearthstonerank')),
            ],
        ),
    ]
