# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubgRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(default='rank name', max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='pubg/images/')),
            ],
        ),
        migrations.CreateModel(
            name='PubgMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_0_20', models.FloatField(default=0)),
                ('marks_21_40', models.FloatField(default=0)),
                ('marks_41_60', models.FloatField(default=0)),
                ('marks_61_80', models.FloatField(default=0)),
                ('marks_81_100', models.FloatField(default=0)),
                ('rank', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='pubg.pubgrank')),
            ],
        ),
        migrations.CreateModel(
            name='PubgDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pubg_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select_champion', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='pubg.pubgrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='pubg.pubgrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='pubg.pubgrank')),
            ],
        ),
        migrations.CreateModel(
            name='PubgTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_V_to_VI', models.FloatField(default=0)),
                ('from_VI_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_V_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='pubg.pubgrank')),
            ],
        ),
    ]
