# Generated by Django 5.0.4 on 2025-05-16 11:52

import booster.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('is_wr_player', models.BooleanField(default=False)),
                ('is_valo_player', models.BooleanField(default=False)),
                ('is_pubg_player', models.BooleanField(default=False)),
                ('is_lol_player', models.BooleanField(default=False)),
                ('is_tft_player', models.BooleanField(default=False)),
                ('is_wow_player', models.BooleanField(default=False)),
                ('is_hearthstone_player', models.BooleanField(default=False)),
                ('is_mobleg_player', models.BooleanField(default=False)),
                ('is_rl_player', models.BooleanField(default=False)),
                ('is_dota2_player', models.BooleanField(default=False)),
                ('is_hok_player', models.BooleanField(default=False)),
                ('is_overwatch2_player', models.BooleanField(default=False)),
                ('is_csgo2_player', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='/booster/images/27/ed5a10fa-3efe-41ed-a5f6-dc518d3393ef.webp', null=True, upload_to=booster.models.profile_image_upload_path)),
                ('about_you', models.TextField(blank=True, max_length=300, null=True)),
                ('can_choose_me', models.BooleanField(blank=True, default=False)),
                ('paypal_account', models.EmailField(max_length=254, null=True, unique=True)),
                ('discord_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_wr_player', models.BooleanField(default=False)),
                ('is_valo_player', models.BooleanField(default=False)),
                ('is_pubg_player', models.BooleanField(default=False)),
                ('is_lol_player', models.BooleanField(default=False)),
                ('is_tft_player', models.BooleanField(default=False)),
                ('is_wow_player', models.BooleanField(default=False)),
                ('is_hearthstone_player', models.BooleanField(default=False)),
                ('is_mobleg_player', models.BooleanField(default=False)),
                ('is_rl_player', models.BooleanField(default=False)),
                ('is_dota2_player', models.BooleanField(default=False)),
                ('is_hok_player', models.BooleanField(default=False)),
                ('is_overwatch2_player', models.BooleanField(default=False)),
                ('is_csgo2_player', models.BooleanField(default=False)),
                ('booster', models.OneToOneField(limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster', to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(related_name='games', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='BoosterPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booster/images')),
                ('approved', models.BooleanField(default=False)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_portfolio', to='booster.booster')),
            ],
        ),
        migrations.CreateModel(
            name='BoosterRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=100)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rank/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_csgo2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 13}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csgo2_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_dota2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dota2_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_hearthstone',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearthstone_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_hok',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hok_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_lol',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lol_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_mobleg',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobleg_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_overwatch2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 12}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overwatch2_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_pubg',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubg_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_rl',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 9}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_tft',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tft_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_valo',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valo_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_wow',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wow_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_wr',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_rank', to='booster.boosterrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='languages',
            field=models.ManyToManyField(to='booster.language'),
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=500, null=True)),
                ('game', models.IntegerField(default=1)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(limit_choices_to={'is_booster': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_rated', to='accounts.baseorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('discord_id', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=300)),
                ('server', models.CharField(max_length=100)),
                ('about_you', models.TextField(max_length=1000)),
                ('country', django_countries.fields.CountryField(max_length=1000)),
                ('agree_privacy', models.BooleanField()),
                ('game', models.ManyToManyField(to='games.game')),
                ('languages', models.ManyToManyField(to='booster.language')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booster/images')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booster.workwithus')),
            ],
        ),
    ]
