# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csgo2PremierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_0_4999', models.FloatField(default=5.42)),
                ('price_5000_7999', models.FloatField(default=6.77)),
                ('price_8000_11999', models.FloatField(default=11.28)),
                ('price_12000_18999', models.FloatField(default=16.28)),
                ('price_19000_20999', models.FloatField(default=30.35)),
                ('price_21000_24999', models.FloatField(default=37.61)),
                ('price_25000_30000', models.FloatField(default=60.17)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Csgo2PremierRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=300)),
                ('start_range', models.IntegerField()),
                ('end_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='csgo2/images/')),
                ('rank_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CsgoFaceitOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_faceit_order', serialize=False, to='accounts.baseorder')),
                ('current_level', models.IntegerField(blank=True, default=1)),
                ('reached_level', models.IntegerField(blank=True, default=1, null=True)),
                ('desired_level', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CsgoFaceitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_1_to_2', models.FloatField(default=16.68)),
                ('from_2_to_3', models.FloatField(default=16.68)),
                ('from_3_to_4', models.FloatField(default=19.43)),
                ('from_4_to_5', models.FloatField(default=20.83)),
                ('from_5_to_6', models.FloatField(default=23.6)),
                ('from_6_to_7', models.FloatField(default=27.77)),
                ('from_7_to_8', models.FloatField(default=34.72)),
                ('from_8_to_9', models.FloatField(default=48.6)),
                ('from_9_to_10', models.FloatField(default=62.48)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Csgo2PremierOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_premier_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_rank', to='csgo2.csgo2premierrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='desired_rank', to='csgo2.csgo2premierrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reached_rank', to='csgo2.csgo2premierrank')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_number', models.PositiveSmallIntegerField(default=5)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='csgo2.csgo2rank')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2DivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_rank', to='csgo2.csgo2rank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='desired_rank', to='csgo2.csgo2rank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reached_rank', to='csgo2.csgo2rank')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_I_to_I_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='csgo2.csgo2rank')),
            ],
        ),
    ]
