# Generated by Django 5.0.4 on 2025-05-16 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLegendsPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='mobile_legends/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileLegendsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='mobile_legends/images/')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLegendsPlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mob_leg_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select_champion', models.BooleanField(blank=True, default=False, null=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mob_leg_last_rank', to='mobileLegends.mobilelegendsplacement')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLegendsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_1', models.FloatField(default=0)),
                ('star_2', models.FloatField(default=0)),
                ('star_3', models.FloatField(default=0)),
                ('star_4', models.FloatField(default=0)),
                ('star_5', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='mobileLegends.mobilelegendsrank')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLegendsDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mobile_legends_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select_champion', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 9)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='mobileLegends.mobilelegendsrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 10)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='mobileLegends.mobilelegendsrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 10)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='mobileLegends.mobilelegendsrank')),
            ],
        ),
        migrations.CreateModel(
            name='MobileLegendsTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_V_to_IV', models.FloatField(default=0)),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_V_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='mobileLegends.mobilelegendsrank')),
            ],
        ),
    ]
